module.exports = {
    apps: [
        {
            name: "Fixture Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=fixture"],
        },
        {
            name: "Lineup Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=lineup"],
        },
        {
            name: "Squad Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=squad"],
        },
        {
            name: "Point Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=point"],
        },
        {
            name: "Leaderboard Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=leaderboard"],
        },
        {
            name: "Cashfree pending payment Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=pendingpayment"],
        },
        {
            name: "Admin Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon"],
        },
        {
            name: "Admin Email Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=email"],
        },
        {
            name: "PrizeBreakup Update Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: [
                "queue:work",
                "--daemon",
                "--queue=CalculateDynamicPrizeBreakup",
            ],
        },
        {
            name: "Cancel Contest Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=CallContestCancel"],
        },
        {
            name: "CalculateEarnings Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=CalculateEarnings"],
        },
        {
            name: "AddCommission Queue",
            script: "artisan",
            interpreter: "php",
            exec_mode: "fork",
            args: ["queue:work", "--daemon", "--queue=AddCommission"],
        },
    ],
};
